name: H2Opulence
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5827
title: H2Opulence // Water Redefined
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#303150'
    - '#1dceb1'
    - '#98e8db'
    - '#656565'
  brandStrength: 0.15413660113699734
  lightness: 0.2127497054170817
  saturation: 0.7092172293923795
  rhythmicContrast: 0.17354038450866938
purpose: []
